# Generated by Django 2.0.4 on 2018-05-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180501_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='blog.Post'),
            preserve_default=False,
        ),
    ]
